server:
  port: ${SERVER_PORT}
  tomcat:
    max-swallow-size: 100MB
    basedir: ./uploads

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

  web:
    resources:
      static-locations: file:./uploads/

app:
  frontend-domain: ${FRONTEND_DOMAIN}

openai:
  api:
    key: ${OPENAI_API_KEY}
